Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -22,6 +22,8 @@ steps:
     echo "##vso[task.setvariable variable=WORK_ITEM_TYPE]${WORK_ITEM_TYPE}"
     echo "##vso[task.setvariable variable=PARENT_WORK_ITEM_ID]${PARENT_WORK_ITEM_ID}"
 
+    createBranch=${{ parameters.AutoBranch.resource.fields['Custom.Criarbranch'] }}
+
     if [[ -z "$WORK_ITEM_ID" ]]; then
       echo "##vso[task.logissue type=error]Work item ID not found."
       exit 1
@@ -31,8 +33,13 @@ steps:
       echo "##vso[task.logissue type=error]Exit on Work item $WORK_ITEM_ID - Invalid type."
       exit 1
     fi
+
+    if [[ "$createBranch" == "false" ]]; then
+      echo "##vso[task.logissue type=error]createBranch is set to false on work item $WORK_ITEM_ID."
+      exit 1
+    fi
   env:
-    WORK_ITEM_ID: ${{ parameters.AutoBranch.resource.id }}
+    WORK_ITEM_ID: ${{ parameters.AutoBranch.resource.workItemId }}
     WORK_ITEM_TYPE: ${{ parameters.AutoBranch.resource.fields['System.WorkItemType'] }}
     PARENT_WORK_ITEM_ID: ${{ parameters.AutoBranch.resource.fields['System.Parent'] }}
   displayName: "Check incoming"
