Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -21,9 +21,25 @@ steps:
     echo "##vso[task.setvariable variable=WORK_ITEM_ID]${WORK_ITEM_ID}"
     echo "##vso[task.setvariable variable=WORK_ITEM_TYPE]${WORK_ITEM_TYPE}"
     echo "##vso[task.setvariable variable=PARENT_WORK_ITEM_ID]${PARENT_WORK_ITEM_ID}"
-        
-    if [[ -z "$WORK_ITEM_ID" ]] || [[ ! "$WORK_ITEM_TYPE" =~ ^($VALID_WORK_ITEM_TYPES)$ ]]; then
-      echo "##vso[task.logissue type=error]Exit on Work item $WORK_ITEM_ID."
+
+    if [[ ${{ parameters.AutoBranch.resource.rev }} -ne 1 ]]; then
+      createBranch=${{ parameters.AutoBranch.resource.fields['Custom.Criarbranch'].newValue }}
+    else
+      createBranch=${{ parameters.AutoBranch.resource.fields['Custom.Criarbranch'] }}
+    fi
+
+    if [[ -z "$WORK_ITEM_ID" ]]; then
+      echo "##vso[task.logissue type=error]Work item ID not found."
+      exit 1
+    fi
+
+    if [[ ! "$WORK_ITEM_TYPE" =~ ^($VALID_WORK_ITEM_TYPES)$ ]]; then
+      echo "##vso[task.logissue type=error]Exit on Work item $WORK_ITEM_ID - Invalid type."
+      exit 1
+    fi
+
+    if [[ "$createBranch" == "false" ]]; then
+      echo "##vso[task.logissue type=error]createBranch is set to false on work item $WORK_ITEM_ID."
       exit 1
     fi
   env:
