Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -21,12 +21,15 @@ steps:
     echo "##vso[task.setvariable variable=WORK_ITEM_ID]${WORK_ITEM_ID}"
     echo "##vso[task.setvariable variable=WORK_ITEM_TYPE]${WORK_ITEM_TYPE}"
     echo "##vso[task.setvariable variable=PARENT_WORK_ITEM_ID]${PARENT_WORK_ITEM_ID}"
+    
+    echo "${{ parameters.AutoBranch.resource.fields['Custom.Criarbranch'].newValue }}"
+    echo "${{ parameters.AutoBranch.resource.rev }}"
 
-    if [[ ${{ parameters.AutoBranch.resource.rev }} -ne 1 ]]; then
-      createBranch=${{ parameters.AutoBranch.resource.fields['Custom.Criarbranch'].newValue }}
-    else
-      createBranch=${{ parameters.AutoBranch.resource.fields['Custom.Criarbranch'] }}
-    fi
+    # if [[ ${{ parameters.AutoBranch.resource.rev }} -ne 1 ]]; then
+    #   createBranch=${{ parameters.AutoBranch.resource.fields['Custom.Criarbranch'].newValue }}
+    # else
+    #   createBranch=${{ parameters.AutoBranch.resource.fields['Custom.Criarbranch'] }}
+    # fi
 
     if [[ -z "$WORK_ITEM_ID" ]]; then
       echo "##vso[task.logissue type=error]Work item ID not found."
@@ -38,10 +41,10 @@ steps:
       exit 1
     fi
 
-    if [[ "$createBranch" == "false" ]]; then
-      echo "##vso[task.logissue type=error]createBranch is set to false on work item $WORK_ITEM_ID."
-      exit 1
-    fi
+    # if [[ "$createBranch" == "false" ]]; then
+    #   echo "##vso[task.logissue type=error]createBranch is set to false on work item $WORK_ITEM_ID."
+    #   exit 1
+    # fi
   env:
     WORK_ITEM_ID: ${{ parameters.AutoBranch.resource.id }}
     WORK_ITEM_TYPE: ${{ parameters.AutoBranch.resource.fields['System.WorkItemType'] }}
